version: '2'
services:
    challenge-app:
        image: challenge
        external_links:
            - challenge-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/challenge
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    challenge-postgresql:
        extends:
            file: postgresql.yml
            service: challenge-postgresql
